
pluginManagement {
    repositories {
        maven {
            // RetroFuturaGradle
            name "GTNH Maven"
            url "https://nexus.gtnewhorizons.com/repository/public/"
            mavenContent {
                includeGroup("com.gtnewhorizons")
                includeGroupByRegex("com\\.gtnewhorizons\\..+")
            }
        }
        maven { url "https://jitpack.io" }
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
    }
}

plugins {
    id 'com.gtnewhorizons.gtnhsettingsconvention' version '1.0.27'
}

// Include the D.TS generator plugin from CustomNPC+ submodule
if (file('CustomNPC-Plus/gradle-plugins/settings.gradle').exists()) {
    includeBuild 'CustomNPC-Plus/gradle-plugins'
}
